/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum290626;

/**
 *
 * @author acer
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbJudul = new javax.swing.JLabel();
        btnMakanan = new javax.swing.JButton();
        btnMinuman = new javax.swing.JButton();
        lbMakanan = new javax.swing.JLabel();
        lbMeja = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtMeja = new javax.swing.JTextField();
        lbHargaMakanan = new javax.swing.JLabel();
        lbHargaMinuman = new javax.swing.JLabel();
        txtMakanan = new javax.swing.JTextField();
        txtMinuman = new javax.swing.JTextField();
        lbTotalHarga = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnSelesai = new javax.swing.JButton();
        lblUangBayar = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();
        txtUangBayar = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbJudul.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbJudul.setText("FORM PEMESANAN MAKANAN");

        btnMakanan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMakanan.setText("MENU MAKANAN");
        btnMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakananActionPerformed(evt);
            }
        });

        btnMinuman.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMinuman.setText("MENU MINUMAN");
        btnMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumanActionPerformed(evt);
            }
        });

        lbMakanan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbMakanan.setText("Nama Makanan ");

        lbMeja.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbMeja.setText("No Meja");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        txtMeja.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lbHargaMakanan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbHargaMakanan.setText("Total Harga Makanan");

        lbHargaMinuman.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbHargaMinuman.setText("Total Harga Minuman");

        txtMakanan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtMakanan.setText("0");
        txtMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakananActionPerformed(evt);
            }
        });

        txtMinuman.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtMinuman.setText("0");

        lbTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbTotalHarga.setText("Total Harga");

        txtTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalHarga.setText("0");
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnSelesai.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        lblUangBayar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUangBayar.setText("Uang Bayar");

        lblKembalian.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblKembalian.setText("Kembalian");

        txtUangBayar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtUangBayar.setText("0");
        txtUangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangBayarActionPerformed(evt);
            }
        });

        txtKembalian.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtKembalian.setText("0");
        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbMakanan)
                                            .addComponent(lbMeja))
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtMeja)))
                                    .addComponent(btnMakanan))
                                .addGap(436, 436, 436)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbHargaMakanan)
                                    .addComponent(lbHargaMinuman)
                                    .addComponent(lbTotalHarga))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMakanan)
                                    .addComponent(txtMinuman)
                                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(421, 421, 421)
                                        .addComponent(btnReset)
                                        .addGap(175, 175, 175)
                                        .addComponent(btnKeluar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMinuman)
                                        .addGap(250, 250, 250)
                                        .addComponent(btnSelesai)))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKembalian)
                                    .addComponent(lblUangBayar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(txtUangBayar))
                                .addGap(65, 65, 65))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(519, 519, 519)
                        .addComponent(lbJudul)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbJudul)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMakanan)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHargaMakanan)
                    .addComponent(txtMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMeja)
                            .addComponent(txtMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHargaMinuman)
                            .addComponent(txtMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalHarga)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMakanan)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMinuman)
                        .addGap(299, 299, 299))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelesai)
                            .addComponent(lblUangBayar)
                            .addComponent(txtUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnReset)
                                    .addComponent(btnKeluar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblKembalian)
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(218, 218, 218))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMakananActionPerformed

    private void btnMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakananActionPerformed
       FormMakanan frm = new FormMakanan(this);
       frm.setVisible(true);
    }//GEN-LAST:event_btnMakananActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed

    String nama = txtNama.getText().trim();
    String meja = txtMeja.getText().trim();

    
    if (nama.isEmpty() || meja.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tunggu dulu! Nama dan No Meja wajib diisi!");
        return; 
    }

    try {
        double totalHarga = Double.parseDouble(txtTotalHarga.getText());
        double uangBayar = Double.parseDouble(txtUangBayar.getText());

        if (uangBayar < totalHarga) {
            javax.swing.JOptionPane.showMessageDialog(this, "Maaf, uang bayar Anda kurang!");
        } else {
            
            double kembalian = uangBayar - totalHarga;
            txtKembalian.setText(String.valueOf(kembalian));
            
            String struk = "=== STRUK PESANAN ===\n"
                         + "Nama: " + nama + "\n"
                         + "Meja: " + meja + "\n"
                         + "Total Tagihan: Rp " + totalHarga + "\n"
                         + "Uang Bayar: Rp " + uangBayar + "\n"
                         + "Kembalian: Rp " + kembalian + "\n"
                         + "=====================";
            javax.swing.JOptionPane.showMessageDialog(this, struk);
        }
    } catch (NumberFormatException e) {
  
        javax.swing.JOptionPane.showMessageDialog(this, "Gunakan angka yang benar untuk kotak pembayaran!");
    }

    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void txtUangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangBayarActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed

    FormMinuman frm = new FormMinuman(this);
    frm.setVisible(true);
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
    txtNama.setText("");
    txtMeja.setText("");
    txtMakanan.setText("0");
    txtMinuman.setText("0");
    txtTotalHarga.setText("0");
    txtUangBayar.setText("0");
    txtKembalian.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       
    int jawaban = javax.swing.JOptionPane.showConfirmDialog(this, 
                  "Apakah Anda yakin ingin menutup aplikasi kasir ini?", 
                  "Konfirmasi Keluar", 
                  javax.swing.JOptionPane.YES_NO_OPTION);
                  
    if (jawaban == javax.swing.JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnKeluarActionPerformed
public void setTotalMakanan(String nilai){
    txtMakanan.setText(nilai);
    hitungGrandTotal(); 
}

public void setTotalMinuman(String nilai){
    txtMinuman.setText(nilai);
    hitungGrandTotal(); 
}

private void hitungGrandTotal() {
    try {
        double makan = Double.parseDouble(txtMakanan.getText());
        double minum = Double.parseDouble(txtMinuman.getText());
        txtTotalHarga.setText(String.valueOf(makan + minum));
    } catch (Exception e) {
        txtTotalHarga.setText("0");
    }
}
    
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new FormUtama().setVisible(true); 
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMakanan;
    private javax.swing.JButton btnMinuman;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JLabel lbHargaMakanan;
    private javax.swing.JLabel lbHargaMinuman;
    private javax.swing.JLabel lbJudul;
    private javax.swing.JLabel lbMakanan;
    private javax.swing.JLabel lbMeja;
    private javax.swing.JLabel lbTotalHarga;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblUangBayar;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtMakanan;
    private javax.swing.JTextField txtMeja;
    private javax.swing.JTextField txtMinuman;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtUangBayar;
    // End of variables declaration//GEN-END:variables
}
