/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum290626;

/**
 *
 * @author acer
 */

public class FormMinuman extends javax.swing.JFrame {

    /**
     * Creates new form FormMinuman
     */
    private FormUtama Utama;

    public FormMinuman(FormUtama Utama) {
        this.Utama = Utama;
        initComponents();
    }
    public FormMinuman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbPatipum = new javax.swing.JCheckBox();
        ckbChamomile = new javax.swing.JCheckBox();
        ckbHijau = new javax.swing.JCheckBox();
        txtPatipum = new javax.swing.JTextField();
        txtChamomile = new javax.swing.JTextField();
        txtHijau = new javax.swing.JTextField();
        cbPatipum = new javax.swing.JComboBox<>();
        cbChamomile = new javax.swing.JComboBox<>();
        cbHijau = new javax.swing.JComboBox<>();
        btnTotalMinuman = new javax.swing.JButton();
        txtTotalMinuman = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        txtTotalPatipum = new javax.swing.JTextField();
        txtTotalChamomile = new javax.swing.JTextField();
        txtTotalHijau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("PIlihan Minuman");

        ckbPatipum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ckbPatipum.setText("Teh Patipum");
        ckbPatipum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbPatipumActionPerformed(evt);
            }
        });

        ckbChamomile.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ckbChamomile.setText("Teh chamomile");
        ckbChamomile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbChamomileActionPerformed(evt);
            }
        });

        ckbHijau.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ckbHijau.setText("Teh Hijau");
        ckbHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbHijauActionPerformed(evt);
            }
        });

        txtPatipum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPatipum.setText("0");
        txtPatipum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatipumActionPerformed(evt);
            }
        });

        txtChamomile.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtChamomile.setText("0");

        txtHijau.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtHijau.setText("0");

        cbPatipum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbPatipum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbPatipum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPatipumActionPerformed(evt);
            }
        });

        cbChamomile.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbChamomile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbChamomile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChamomileActionPerformed(evt);
            }
        });

        cbHijau.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbHijau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHijauActionPerformed(evt);
            }
        });

        btnTotalMinuman.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnTotalMinuman.setText("Total Harga");
        btnTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMinumanActionPerformed(evt);
            }
        });

        txtTotalMinuman.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalMinuman.setText("0");
        txtTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMinumanActionPerformed(evt);
            }
        });

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        txtTotalPatipum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalPatipum.setText("0");

        txtTotalChamomile.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalChamomile.setText("0");

        txtTotalHijau.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalHijau.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTotalMinuman)
                .addGap(103, 103, 103)
                .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(729, 729, 729)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbHijau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHijau, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ckbChamomile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtChamomile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ckbPatipum)
                                .addGap(140, 140, 140)
                                .addComponent(txtPatipum, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbPatipum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChamomile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalPatipum, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtTotalChamomile)
                            .addComponent(txtTotalHijau))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbPatipum)
                            .addComponent(txtPatipum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPatipum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalPatipum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbChamomile)
                            .addComponent(txtChamomile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChamomile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalChamomile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbHijau)
                            .addComponent(txtHijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHijau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addComponent(btnTotalMinuman)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatipumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatipumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatipumActionPerformed

    private void ckbPatipumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPatipumActionPerformed
        txtPatipum.setText("10000");
    }//GEN-LAST:event_ckbPatipumActionPerformed

    private void ckbChamomileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbChamomileActionPerformed
        txtChamomile.setText("30000");
    }//GEN-LAST:event_ckbChamomileActionPerformed

    private void ckbHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbHijauActionPerformed
        txtHijau.setText("5000");
    }//GEN-LAST:event_ckbHijauActionPerformed

    private void cbPatipumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPatipumActionPerformed
        int jumlah = (int)cbPatipum.getSelectedIndex();
        double harga = Double.parseDouble(txtPatipum.getText());
        double total = jumlah*harga;
        txtTotalPatipum.setText(Double.toString(total));
    }//GEN-LAST:event_cbPatipumActionPerformed

    private void cbChamomileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChamomileActionPerformed
        int jumlah = (int)cbChamomile.getSelectedIndex();
        double harga = Double.parseDouble(txtChamomile.getText());
        double total = jumlah*harga;
        txtTotalChamomile.setText(Double.toString(total));
    }//GEN-LAST:event_cbChamomileActionPerformed

    private void cbHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHijauActionPerformed
        int jumlah = (int)cbHijau.getSelectedIndex();
        double harga = Double.parseDouble(txtHijau.getText());
        double total = jumlah*harga;
        txtTotalHijau.setText(Double.toString(total));
    }//GEN-LAST:event_cbHijauActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMinuman.getText();
        Utama.setTotalMinuman(total); 
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMinumanActionPerformed
        
    }//GEN-LAST:event_txtTotalMinumanActionPerformed

    private void btnTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMinumanActionPerformed

    double a = Double.parseDouble(txtTotalPatipum.getText());
    double b = Double.parseDouble(txtTotalChamomile.getText());
    double c = Double.parseDouble(txtTotalHijau.getText());
    double total = a + b + c;
    txtTotalMinuman.setText(String.valueOf(total));

    }//GEN-LAST:event_btnTotalMinumanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalMinuman;
    private javax.swing.JComboBox<String> cbChamomile;
    private javax.swing.JComboBox<String> cbHijau;
    private javax.swing.JComboBox<String> cbPatipum;
    private javax.swing.JCheckBox ckbChamomile;
    private javax.swing.JCheckBox ckbHijau;
    private javax.swing.JCheckBox ckbPatipum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtChamomile;
    private javax.swing.JTextField txtHijau;
    private javax.swing.JTextField txtPatipum;
    private javax.swing.JTextField txtTotalChamomile;
    private javax.swing.JTextField txtTotalHijau;
    private javax.swing.JTextField txtTotalMinuman;
    private javax.swing.JTextField txtTotalPatipum;
    // End of variables declaration//GEN-END:variables
}
