/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum290626;

/**
 *
 * @author acer
 */

public class FormMakanan extends javax.swing.JFrame {

    /**
     * Creates new form FormMakanan
     */
    private FormUtama utama;
    public FormMakanan() {
        initComponents();
    }

    public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbNasgor = new javax.swing.JCheckBox();
        ckbMigor = new javax.swing.JCheckBox();
        ckbMire = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtMigor = new javax.swing.JTextField();
        txtMire = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbMigor = new javax.swing.JComboBox<>();
        cbMire = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalMigor = new javax.swing.JTextField();
        txtTotalMire = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("PILIHAN MENU MAKANAN");

        ckbNasgor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ckbNasgor.setText("Nasi Goreng");
        ckbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNasgorActionPerformed(evt);
            }
        });

        ckbMigor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ckbMigor.setText("Mie Goreng");
        ckbMigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMigorActionPerformed(evt);
            }
        });

        ckbMire.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ckbMire.setText("Mie Rebus");
        ckbMire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMireActionPerformed(evt);
            }
        });

        txtNasgor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtNasgor.setText("0");

        txtMigor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtMigor.setText("0");

        txtMire.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtMire.setText("0");

        cbNasgor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasgorActionPerformed(evt);
            }
        });

        cbMigor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbMigor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMigorActionPerformed(evt);
            }
        });

        cbMire.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbMire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMireActionPerformed(evt);
            }
        });

        txtTotalNasgor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalNasgor.setText("0");

        txtTotalMigor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalMigor.setText("0");

        txtTotalMire.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalMire.setText("0");

        txtTotalMakanan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtTotalMakanan.setText("0");

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnTotal.setText("Total Harga");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbMigor)
                            .addComponent(ckbMire)
                            .addComponent(ckbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtMigor)
                            .addComponent(txtMire))
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalNasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtTotalMigor)
                            .addComponent(txtTotalMire)
                            .addComponent(txtTotalMakanan)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addComponent(btnKembali)))
                .addGap(523, 523, 523))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbNasgor)
                    .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMigor)
                    .addComponent(txtMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbMire)
                            .addComponent(txtMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalMire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(129, 129, 129))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNasgorActionPerformed
       txtNasgor.setText("15000");
    }//GEN-LAST:event_ckbNasgorActionPerformed

    private void ckbMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMigorActionPerformed
        txtMigor.setText("10000");
    }//GEN-LAST:event_ckbMigorActionPerformed

    private void ckbMireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMireActionPerformed
        txtMire.setText("8000");
    }//GEN-LAST:event_ckbMireActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int)cbNasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtNasgor.getText());
        double total = jumlah*harga;
        txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbMigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMigorActionPerformed
        int jumlah = (int)cbMigor.getSelectedIndex();
        double harga = Double.parseDouble(txtMigor.getText());
        double total = jumlah*harga;
        txtTotalMigor.setText(Double.toString(total));
    }//GEN-LAST:event_cbMigorActionPerformed

    private void cbMireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMireActionPerformed
         int jumlah = (int)cbMire.getSelectedIndex();
        double harga = Double.parseDouble(txtMire.getText());
        double total = jumlah*harga;
        txtTotalMire.setText(Double.toString(total));
    }//GEN-LAST:event_cbMireActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
       double a = Double.parseDouble(txtTotalNasgor.getText());
       double b = Double.parseDouble(txtTotalMigor.getText());
       double c = Double.parseDouble(txtTotalMire.getText());
       double total = a+b+c;
       txtTotalMakanan.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMakanan.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbMigor;
    private javax.swing.JComboBox<String> cbMire;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JCheckBox ckbMigor;
    private javax.swing.JCheckBox ckbMire;
    private javax.swing.JCheckBox ckbNasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMigor;
    private javax.swing.JTextField txtMire;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMigor;
    private javax.swing.JTextField txtTotalMire;
    private javax.swing.JTextField txtTotalNasgor;
    // End of variables declaration//GEN-END:variables
}
